### PR TITLE
Update metadata

### PR DESCRIPTION
**Pull request by vipulgupta2048**

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed to bfc5e91.  Noted these things;

* [ ] your .gitignore file again doesn't finish the last line; how does this keep happening, have you an editor that doesn't show it?

* [ ] you've made the pull request against the sugarlabs repository rather than the original repository, and switched the *repository* metadata to sugarlabs.  @samdroid-apps, is this okay by you?

**Comment by vipulgupta2048** [comment]
@quozl  :sweat: I am really sorry about it. 
- My script automatically creates a .gitignore if it doesn't find one. I have fixed this problem just today only by putting put `\n` after each entity. I use mousepad as my text editor for quick fixes, it doesn't really show line endings. I will look up a setting for it ASAP. So sorry for the inconvenience.
- I did see that, I thought this was actually the way to go. I will revert it if @samdroid-apps says so. Np.

**Comment by samdroid-apps** [comment]
Yeah that is fine regarding making the sugarlabs version the referenced version.

**Comment by vipulgupta2048** [comment]
Thank you @samdroid-apps :hatching_chick:

**Comment by quozl** [comment]
@samdroid-apps, thanks.

@vipulgupta2048 said
> my script automatically

You might check `git diff` before `git commit`.  Check that you understand everything changed.  I don't know what editor and associated tool chain you are using; but I use emacs with magit, which lets me see fine grained detail of change and revert tiny parts of a change until I'm happy with it.  There are probably some other good editors and tools which let you do the same.

**Pull request merged**
